### PR TITLE
Add Otel support for ecs CDK

### PR DESCRIPTION
**Pull request by froumieh**
Add Otel support for ecs

### CODE REVIEW

**Review by erikrj — CHANGES_REQUESTED** [review]
Please use ECR public by default for the OTEL image. The default is DockerHub how you have it configured.
Allow the user to override the image to be used for OTEL.
Do we need to add health checks to the OTEL container? 
Do we need to consider this an essential container in the task definition?
Do we need to automatically add metric, log and xray permissions when OTEL is enabled?

Please make sure these changes are also reflected in the terraform version.

**Comment by froumieh** [comment]
>Please use ECR public by default for the OTEL image. The default is DockerHub how you have it configured. 

I changed that. Currently we are testing with a config from parameter store /payment/dev/otel/config

>Allow the user to override the image to be used for OTEL. 

Done

> Do we need to add health checks to the OTEL container? 

I've added health checks

> Do we need to consider this an essential container in the task definition? 

It's actually essential by default, but I don't think we should make it essential, we shouldn't interrupt business if Otel task not working. @tvc123 your thoughts?

> Do we need to automatically add metric, log and xray permissions when OTEL is enabled?

I'm not sure if these permissions are needed. @taunyamakura @tvc123 ?

> Please make sure these changes are also reflected in the terraform version.

I will

**Comment by erikrj** [comment]
Doesn't look like my TODO items were addressed. Please get those done so we can get this released. I have re-synced your branch with develop.

**Comment by taunyamakura** [comment]
> I have added a bunch of TODOs. See https://github.com/truemark/cdk/blob/otel-ecs/aws-ecs/lib/standard-fargate-service.ts. When ready, re-open the PR.

I have addressed the below todos:
// TODO This should be otelConfigPath. The jsdoc comment also needs to explain this and otelSsmConfigContentParam conflict and which takes precedence if both are set.
// TODO This should be otelAmpWorkSpaceId
// TODO Just change this to "Otel"
// TODO If otelAmpWorkSpaceId is not set, don't added this
// TODO If otelSsmConfigContentParam, this shouldn't be added
'/overwatch/otel/ecs-default-config' // TODO The CDK library should know nothing of overwatch. Don't supply a default.
// TODO Allow this to be overridden and the default to be just "otel-collector"
// TODO Should be the same as containerName
// TODO Should thgis be allowed to be overridden from props?
// TODO Is this a good default? Where did it come from? Please add a comment to help people when reading the code.
// TODO Create an OtelConfig interface and move these properties to it. Create a new "otel" property in this interface to hold the OtelConfig.

**Pull request merged**
